const npcBuyPrices = {
    "BONE": 8,
    "BROWN_MUSHROOM": 25,
    "CACTUS": 15,
    "CARROT_ITEM": 10,
    "COAL": 4,
    "COBBLESTONE": 3,
    "ENCHANTED_BONE_MEAL": 2,
    "EXP_BOTTLE": 30,
    "FLINT": 6,
    "GHAST_TEAR": 200,
    "GOLD_INGOT": 5.5,
    "GRAVEL": 4.3,
    "ICE": 1,
    "INK_SACK:3": 5,
    "IRON_INGOT": 5,
    "LOG": 5,
    "LOG:1": 5,
    "LOG:2": 5,
    "LOG:3": 5,
    "LOG_2": 5,
    "LOG_2:1": 5,
    "MAGMA_CREAM": 20,
    "MELON": 4,
    "NETHERRACK": 2,
    "NETHER_STALK": 10,
    "OBSIDIAN": 99,
    "ONYX": 100,
    "POTATO_ITEM": 10,
    "PACKED_ICE": 9,
    "PUMPKIN": 25,
    "RABBIT_FOOT": 10,
    "RAW_FISH": 20,
    "RAW_FISH:1": 30,
    "RAW_FISH:2": 100,
    "RAW_FISH:3": 40,
    "REDSTONE": 4,
    "RED_MUSHROOM": 25,
    "RED_ROSE": 50,
    "ROTTEN_FLESH": 8,
    "SAND": 4,
    "SLIME_BALL": 14,
    "SPONGE": 800,
    "SPIDER_EYE": 12,
    "STRING": 10,
    "SUGAR_CANE": 10,
    "SULPHUR": 10,
    "WHEAT": 10,
    "WOOL": 32,
    "YELLOW_FLOWER": 50
}

const humanReadables = {
    "BONE": "Bone",
    "BROWN_MUSHROOM": "Brown Mushroom",
    "CACTUS": "Cactus",
    "CARROT_ITEM": "Carrot",
    "COAL": "Coal",
    "COBBLESTONE": "Cobblestone",
    "ENCHANTED_BONE_MEAL": "Enchanted Bone Meal",
    "EXP_BOTTLE": "Bottle of Experience",
    "FLINT": "Flint",
    "GHAST_TEAR": "Ghast Tear",
    "GOLD_INGOT": "Gold Ingot",
    "GRAVEL": "Gravel",
    "ICE": "Ice",
    "INK_SACK:3": "Cocoa Bean",
    "IRON_INGOT": "Iron Ingot",
    "LOG": "Oak Log",
    "LOG:1": "Spruce Wood",
    "LOG:2": "Birch Wood",
    "LOG_2:1": "Dark Oak",
    "LOG_2": "Acacia Wood",
    "LOG:3": "Jungle Wood",
    "MAGMA_CREAM": "Magma Cream",
    "MELON": "Melon",
    "NETHERRACK": "Netherrack",
    "NETHER_STALK": "Nether Wart",
    "OBSIDIAN": "Obsidian",
    "ONYX": "Onyx",
    "PACKED_ICE": "Packed Ice",
    "POTATO_ITEM": "Potato",
    "PUMPKIN": "Pumpkin",
    "RABBIT_FOOT": "Rabbit Foot",
    "RAW_FISH": "Raw Fish",
    "RAW_FISH:1": "Raw Salmon",
    "RAW_FISH:2": "Clownfish",
    "RAW_FISH:3": "Pufferfish",
    "REDSTONE": "Redstone Dust",
    "RED_MUSHROOM": "Red Mushroom",
    "RED_ROSE": "Poppy",
    "ROTTEN_FLESH": "Rotten Flesh",
    "SAND": "Sand",
    "SLIME_BALL": "Slime Ball",
    "SPIDER_EYE": "Spider Eye",
    "SPONGE": "Sponge",
    "STRING": "String",
    "SUGAR_CANE": "Sugar Cane",
    "SULPHUR": "Gunpowder",
    "WHEAT": "Wheat",
    "WOOL": "White Wool",
    "YELLOW_FLOWER": "Dandelion"
}

const defaultOptionDisplay = {
    "sort-by-profit": "Profit",
    "sort-by-name": "Name",
    "sort-by-cost": "Cost",
    "sort-by-sellPrice": "Sell Price"
}
